/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReadmeRouteImport } from './routes/readme'
import { Route as NewRouteImport } from './routes/new'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsApiKeysRouteImport } from './routes/settings.api-keys'
import { Route as PromptIdRouteImport } from './routes/prompt.$id'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as PromptIdHistoryRouteImport } from './routes/prompt.$id.history'
import { Route as PromptIdEditRouteImport } from './routes/prompt.$id.edit'
import { Route as ApiPublicV1PromptsRouteImport } from './routes/api.public.v1.prompts'
import { Route as ApiPublicV1HealthRouteImport } from './routes/api.public.v1.health'
import { Route as ApiPublicV1PromptsIdRouteImport } from './routes/api.public.v1.prompts.$id'
import { Route as ApiPublicV1PromptsIdRenderRouteImport } from './routes/api.public.v1.prompts.$id.render'

const ReadmeRoute = ReadmeRouteImport.update({
  id: '/readme',
  path: '/readme',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptIdRoute = PromptIdRouteImport.update({
  id: '/prompt/$id',
  path: '/prompt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const PromptIdHistoryRoute = PromptIdHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PromptIdRoute,
} as any)
const PromptIdEditRoute = PromptIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PromptIdRoute,
} as any)
const ApiPublicV1PromptsRoute = ApiPublicV1PromptsRouteImport.update({
  id: '/api/public/v1/prompts',
  path: '/api/public/v1/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1HealthRoute = ApiPublicV1HealthRouteImport.update({
  id: '/api/public/v1/health',
  path: '/api/public/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PromptsIdRoute = ApiPublicV1PromptsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1PromptsRoute,
} as any)
const ApiPublicV1PromptsIdRenderRoute =
  ApiPublicV1PromptsIdRenderRouteImport.update({
    id: '/render',
    path: '/render',
    getParentRoute: () => ApiPublicV1PromptsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/readme': typeof ReadmeRoute
  '/admin/audit': typeof AdminAuditRoute
  '/prompt/$id': typeof PromptIdRouteWithChildren
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/prompt/$id/edit': typeof PromptIdEditRoute
  '/prompt/$id/history': typeof PromptIdHistoryRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/prompts': typeof ApiPublicV1PromptsRouteWithChildren
  '/api/public/v1/prompts/$id': typeof ApiPublicV1PromptsIdRouteWithChildren
  '/api/public/v1/prompts/$id/render': typeof ApiPublicV1PromptsIdRenderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/readme': typeof ReadmeRoute
  '/admin/audit': typeof AdminAuditRoute
  '/prompt/$id': typeof PromptIdRouteWithChildren
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/prompt/$id/edit': typeof PromptIdEditRoute
  '/prompt/$id/history': typeof PromptIdHistoryRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/prompts': typeof ApiPublicV1PromptsRouteWithChildren
  '/api/public/v1/prompts/$id': typeof ApiPublicV1PromptsIdRouteWithChildren
  '/api/public/v1/prompts/$id/render': typeof ApiPublicV1PromptsIdRenderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/readme': typeof ReadmeRoute
  '/admin/audit': typeof AdminAuditRoute
  '/prompt/$id': typeof PromptIdRouteWithChildren
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/prompt/$id/edit': typeof PromptIdEditRoute
  '/prompt/$id/history': typeof PromptIdHistoryRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/prompts': typeof ApiPublicV1PromptsRouteWithChildren
  '/api/public/v1/prompts/$id': typeof ApiPublicV1PromptsIdRouteWithChildren
  '/api/public/v1/prompts/$id/render': typeof ApiPublicV1PromptsIdRenderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/favorites'
    | '/library'
    | '/login'
    | '/new'
    | '/readme'
    | '/admin/audit'
    | '/prompt/$id'
    | '/settings/api-keys'
    | '/prompt/$id/edit'
    | '/prompt/$id/history'
    | '/api/public/v1/health'
    | '/api/public/v1/prompts'
    | '/api/public/v1/prompts/$id'
    | '/api/public/v1/prompts/$id/render'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/favorites'
    | '/library'
    | '/login'
    | '/new'
    | '/readme'
    | '/admin/audit'
    | '/prompt/$id'
    | '/settings/api-keys'
    | '/prompt/$id/edit'
    | '/prompt/$id/history'
    | '/api/public/v1/health'
    | '/api/public/v1/prompts'
    | '/api/public/v1/prompts/$id'
    | '/api/public/v1/prompts/$id/render'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/favorites'
    | '/library'
    | '/login'
    | '/new'
    | '/readme'
    | '/admin/audit'
    | '/prompt/$id'
    | '/settings/api-keys'
    | '/prompt/$id/edit'
    | '/prompt/$id/history'
    | '/api/public/v1/health'
    | '/api/public/v1/prompts'
    | '/api/public/v1/prompts/$id'
    | '/api/public/v1/prompts/$id/render'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  ReadmeRoute: typeof ReadmeRoute
  PromptIdRoute: typeof PromptIdRouteWithChildren
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  ApiPublicV1HealthRoute: typeof ApiPublicV1HealthRoute
  ApiPublicV1PromptsRoute: typeof ApiPublicV1PromptsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/readme': {
      id: '/readme'
      path: '/readme'
      fullPath: '/readme'
      preLoaderRoute: typeof ReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt/$id': {
      id: '/prompt/$id'
      path: '/prompt/$id'
      fullPath: '/prompt/$id'
      preLoaderRoute: typeof PromptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/prompt/$id/history': {
      id: '/prompt/$id/history'
      path: '/history'
      fullPath: '/prompt/$id/history'
      preLoaderRoute: typeof PromptIdHistoryRouteImport
      parentRoute: typeof PromptIdRoute
    }
    '/prompt/$id/edit': {
      id: '/prompt/$id/edit'
      path: '/edit'
      fullPath: '/prompt/$id/edit'
      preLoaderRoute: typeof PromptIdEditRouteImport
      parentRoute: typeof PromptIdRoute
    }
    '/api/public/v1/prompts': {
      id: '/api/public/v1/prompts'
      path: '/api/public/v1/prompts'
      fullPath: '/api/public/v1/prompts'
      preLoaderRoute: typeof ApiPublicV1PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/health': {
      id: '/api/public/v1/health'
      path: '/api/public/v1/health'
      fullPath: '/api/public/v1/health'
      preLoaderRoute: typeof ApiPublicV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/prompts/$id': {
      id: '/api/public/v1/prompts/$id'
      path: '/$id'
      fullPath: '/api/public/v1/prompts/$id'
      preLoaderRoute: typeof ApiPublicV1PromptsIdRouteImport
      parentRoute: typeof ApiPublicV1PromptsRoute
    }
    '/api/public/v1/prompts/$id/render': {
      id: '/api/public/v1/prompts/$id/render'
      path: '/render'
      fullPath: '/api/public/v1/prompts/$id/render'
      preLoaderRoute: typeof ApiPublicV1PromptsIdRenderRouteImport
      parentRoute: typeof ApiPublicV1PromptsIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PromptIdRouteChildren {
  PromptIdEditRoute: typeof PromptIdEditRoute
  PromptIdHistoryRoute: typeof PromptIdHistoryRoute
}

const PromptIdRouteChildren: PromptIdRouteChildren = {
  PromptIdEditRoute: PromptIdEditRoute,
  PromptIdHistoryRoute: PromptIdHistoryRoute,
}

const PromptIdRouteWithChildren = PromptIdRoute._addFileChildren(
  PromptIdRouteChildren,
)

interface ApiPublicV1PromptsIdRouteChildren {
  ApiPublicV1PromptsIdRenderRoute: typeof ApiPublicV1PromptsIdRenderRoute
}

const ApiPublicV1PromptsIdRouteChildren: ApiPublicV1PromptsIdRouteChildren = {
  ApiPublicV1PromptsIdRenderRoute: ApiPublicV1PromptsIdRenderRoute,
}

const ApiPublicV1PromptsIdRouteWithChildren =
  ApiPublicV1PromptsIdRoute._addFileChildren(ApiPublicV1PromptsIdRouteChildren)

interface ApiPublicV1PromptsRouteChildren {
  ApiPublicV1PromptsIdRoute: typeof ApiPublicV1PromptsIdRouteWithChildren
}

const ApiPublicV1PromptsRouteChildren: ApiPublicV1PromptsRouteChildren = {
  ApiPublicV1PromptsIdRoute: ApiPublicV1PromptsIdRouteWithChildren,
}

const ApiPublicV1PromptsRouteWithChildren =
  ApiPublicV1PromptsRoute._addFileChildren(ApiPublicV1PromptsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  ReadmeRoute: ReadmeRoute,
  PromptIdRoute: PromptIdRouteWithChildren,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  ApiPublicV1HealthRoute: ApiPublicV1HealthRoute,
  ApiPublicV1PromptsRoute: ApiPublicV1PromptsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
